services:
  - type: web
    name: ai-resume-server
    runtime: node
    repo: https://github.com/rohanshelar991/ai-resume-builder
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8081
